version: '3.8'

services:
  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_SERVER=localhost
      - POSTGRES_PORT=6432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@654321
      - POSTGRES_DB=crawler_sgk
    env_file:
      - .env

