version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@654321
      - POSTGRES_DB=crawler_sgk
    ports:
      - '6432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@654321
      - POSTGRES_DB=crawler_sgk
    depends_on:
      - db
    volumes:
      - ./download:/app/download

volumes:
  postgres_data:
